### ISSUE TITLE
Shell script to start Bassa servers at once

### ISSUE THREAD

**Issue by Nuwini** [scorelab/Bassa#101]
In the current project there is no script to start all the three Bassa servers at once. Therefore, writing a shell script to start Bassa servers at once will make users comfortable. I will send a PR shortly.

**Comment by saisankargochhayat** [comment]
This seems like a good idea .

**Comment by kmehant** [comment]
I would love to work on this, Im a GCI student this year contributing to Scorelab. I would need to some guidance to start.

**Comment by saisankargochhayat** [comment]
@kmehant Are you done with the local setup of the project?

**Comment by kmehant** [comment]
@saisankargochhayat I tried to run gulp serve from ui folder, i ended up with the following error.

```
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/dsatya/Desktop/mehant/Bassa/ui/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/Users/dsatya/Desktop/mehant/Bassa/ui/gulpfile.js:12:23)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
```

**Comment by saisankargochhayat** [comment]
Have you followed all the instructions and are you on a Linux distribution ?

**Comment by kmehant** [comment]
@saisankargochhayat I removed the local instance and will reinstall again :) Will ping you soon on it.

**Comment by azisnaufal** [comment]
@kmehant That is because you use higher version of node js. This Bassa project only work on v6.xx version

**Comment by kmehant** [comment]
Thanks man :) I realized later and was able to setup.

**Comment by navanchauhan** [comment]
what are the 3 servers and commands to start them?(I am a fellow GCI participant)

**Comment by agentmilindu** [comment]
@Nuwini @kmehant I think other than running the UI and Core directly, we should use something like http://supervisord.org/ to run them because supervisor will start the process if it got crashed.

**Comment by kmehant** [comment]
@agentmilindu I will go through supervisord and work on this issue.

**Comment by iammosespaulr** [comment]
hey i had already submitted a pull request for that earlier
