### ISSUE TITLE
gulp serve error due to broken packages

### ISSUE THREAD

**Issue by Asutosh989** [scorelab/Bassa#432]
On running `gulp serve`, I got an error as follows : -

/Documents/gsoc/Bassa/ui/node_modules/require-dir/index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/home/asutosh/Documents/gsoc/Bassa/ui/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/home/asutosh/Documents/gsoc/Bassa/ui/gulpfile.js:12:23)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)

I am using node8.9 and I found out that Bassa uses some deprecated packages which is not supported by node8.9

**Comment by Asutosh989** [comment]
I have a fix for this and would be creating a PR shortly.

**Comment by Asutosh989** [comment]
I think the issue is solved successfully with the PR #433 . So I am closing the issue.
