### ISSUE TITLE
Readme Update required to specify the MySQL Server version(on WIndows)

### ISSUE THREAD

**Issue by aakashbansal** [scorelab/Bassa#486]
Readme.md needs to be updated and it should mention the details regarding MySQL Server version that is required to be installed on Windows.

The latest MySQL Server 8.x introduces something called caching_sha2_password' plugin that does not work with the existing codebase and gives the follwing error : 

-----------------------------------------------------------------------------------
ERROR:initializer:Exception on /api/login [POST]
Traceback (most recent call last):
File "C:\Users\Aakash\AppData\Local\Programs\Python\Python36\lib\site-packages\flask-0.10.1-py3.6.egg\flask\app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\Aakash\AppData\Local\Programs\Python\Python36\lib\site-packages\flask-0.10.1-py3.6.egg\flask\app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\Aakash\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors-2.1.2-py3.6.egg\flask_cors\extension.py", line 188, in wrapped_function
return cors_after_request(app.make_response(f(args, *kwargs)))
File "C:\Users\Aakash\AppData\Local\Programs\Python\Python36\lib\site-packages\flask-0.10.1-py3.6.egg\flask\app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\Aakash\AppData\Local\Programs\Python\Python36\lib\site-packages\flask-0.10.1-py3.6.egg\flask_compat.py", line 33, in reraise
raise value
File "C:\Users\Aakash\AppData\Local\Programs\Python\Python36\lib\site-packages\flask-0.10.1-py3.6.egg\flask\app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\Aakash\AppData\Local\Programs\Python\Python36\lib\site-packages\flask-0.10.1-py3.6.egg\flask\app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](req.view_args)
File "D:\Bassa\components\core\routes\User.py", line 15, in login
if user_login(userName, password):
File "D:\Bassa\components\core\UserManager.py", line 11, in user_login
db = threadpool.connect()
File "C:\Users\Aakash\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy-1.1.9-py3.6-win-amd64.egg\sqlalchemy\pool.py", line 387, in connect
return _ConnectionFairy._checkout(self)
File "C:\Users\Aakash\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy-1.1.9-py3.6-win-amd64.egg\sqlalchemy\pool.py", line 775, in _checkout
raise exc.InvalidRequestError("This connection is closed")
sqlalchemy.exc.InvalidRequestError: This connection is closed

--------------------------------------------------------------------------------------------

On further investigating the issue on a local dummy project, this turned out to be exact issue : 
------------------------------------------------------------------------------------
Authentication plugin 'caching_sha2_password' cannot be loaded.
-----------------------------------------------------------------------------------

This issue can be solved in one of two ways:

1. Either downgrade the MySQL Server to 5.7.x.
2. Change the password encryption method for MySQL Server. 
 Refer this : https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded

The first method is easier.

**Comment by aakashbansal** [comment]
I can work on changing the Readme file. No issues.

**Comment by VibhorCodecianGupta** [comment]
Huge life saver. Thanks!

**Comment by aakashbansal** [comment]
Yeah! It literally took me more than a day and half to figure it out. Thought fellow contributors should know about this. :)

**Comment by aakashbansal** [comment]
I updated the Readme. Here is the PR #487

**Comment by aakashbansal** [comment]
So instead of the main Readme.md, i have updated the [Windows Installation Guide](https://github.com/scorelab/Bassa/wiki/Windows-Installation-Guide) to reflect the required changes. I'm closing this issue now.
