### ISSUE TITLE
TypeError: cannot serialize 'Hub' object

### ISSUE THREAD

**Issue by tintinmovie** [scorelab/Bassa#589]
When starting the download process, nothing occurs. Looking at the log file shows this error:
```
Traceback (most recent call last):
  File "C:\Users\Benan\Documents\Coding\GCI_2018\Bassa\Bassa\components\core\routes\Download.py", line 24, in start
    p.start()
  File "c:\users\benan\appdata\local\programs\python\python36\Lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "c:\users\benan\appdata\local\programs\python\python36\Lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\users\benan\appdata\local\programs\python\python36\Lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\users\benan\appdata\local\programs\python\python36\Lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\users\benan\appdata\local\programs\python\python36\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot serialize 'Hub' object
```

## Your Environment

* Operating System and version (desktop or mobile): Windows 10

**Comment by kmehant** [comment]
@tintinmovie This seems some issue with **python pickling**, especially on windows operating system. This issue is not related to Bassa API server so closing this for now.
